name: tc
channels:
  - defaults
  - conda-forge
  - dharpa
dependencies:
  - pandas
  - streamlit-aggrid
  - google-api-python-client
  - numpy
  - google-auth-httplib2
  - plotly
  - python=3.9
  - streamlit
  - pillow